services:
  barnacle:
    build: .
    depends_on:
      - redis
    environment:
      BARNACLE_REDIS_HOST: redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: "barnacle"
    driver: bridge
